name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    integrationtests:
        runs-on: ubuntu-latest
        steps:
            # Checkout the Repo
            - uses: actions/checkout@v2

            # Install Node 16
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            # Install dependencies
            - run: npm install

            # Run tests
            - run: npm test

    deploy:
        needs: integrationtests
        runs-on: ubuntu-latest
        environment:
            name: Heroku # naam van mijn environment op GitHub
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.API_KEY_HEROKU}}
                  heroku_app_name: shareameal-api-lucas
                  heroku_email: l.dekleijn2@student.avans.nl